name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Fly.io CLI
        run: |
          curl -fsSL https://fly.io/install.sh | sh

      - name: Authenticate with Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          fly auth token $FLY_API_TOKEN

      - name: Deploy FastAPI + Nginx
        run: |
          fly deploy