name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to AWS Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          cd /home/ec2-user/fastapi-app
          git pull origin main
          source fastapi-env/bin/activate
          pip install -r requirements.txt
          sudo cat /etc/nginx/conf.d/fastapi.conf
          sudo systemctl restart nginx
          sudo systemctl restart fastapi